/** Classic glyph map — existing Phosphor aliases already used by Studio glass. */

import type { ElementType } from 'react';
import type { IconMeaning } from '../shared/icon-meanings';
import {
  Activity, AlertOctagon, AlertTriangle, Archive, ArrowUpDown, Award,
  BarChart3, Briefcase, Building2, Calendar, Car, Check, CheckCircle2,
  ClipboardList, Clock, DollarSign, Download, Eye, FileSpreadsheet,
  FileText, Filter, Flag, Gauge, GraduationCap, HardDrive, HardHat,
  HeartHandshake, LayoutGrid, Layers, List, Package, Percent, Pin, Plus,
  RefreshCw, SearchIcon, Settings, ShieldCheck, ShoppingCart, Sparkles,
  Star, Table2, Target, Trash2, TrendingUp, UserCheck, Users, Wrench, Zap,
  Pencil, CalendarDays, Hash, Send, CheckSquare, XCircle,
} from '../icons';

export const CLASSIC_ICONS: Record<IconMeaning, ElementType> = {
  employees: Users,
  artisans: HardHat,
  'nec-staff': Briefcase,
  'salaried-staff': Briefcase,
  'permanent-staff': UserCheck,
  'grid-view': LayoutGrid,
  'list-view': List,
  'table-view': Table2,
  'sheet-view': FileSpreadsheet,
  search: SearchIcon,
  filter: Filter,
  sort: ArrowUpDown,
  edit: Pencil,
  archive: Archive,
  analytics: BarChart3,
  refresh: RefreshCw,
  download: Download,
  plus: Plus,
  close: XCircle,
  warning: AlertTriangle,
  success: CheckCircle2,
  danger: Trash2,
  clock: Clock,
  calendar: Calendar,
  check: Check,
  pending: Clock,
  active: CheckCircle2,
  inactive: AlertTriangle,
  equipment: Gauge,
  maintenance: Settings,
  breakdown: AlertTriangle,
  availability: Percent,
  documents: FileText,
  storage: HardDrive,
  starred: Star,
  spares: Package,
  value: DollarSign,
  'out-of-stock': AlertOctagon,
  'low-stock': AlertTriangle,
  categories: BarChart3,
  drivers: Car,
  departments: Building2,
  requisition: ShoppingCart,
  cost: DollarSign,
  critical: Flag,
  notice: FileText,
  pinned: Pin,
  expired: Clock,
  training: GraduationCap,
  compliance: ShieldCheck,
  valid: CheckCircle2,
  'due-soon': Calendar,
  issues: Hash,
  recipients: Users,
  care: HeartHandshake,
  submitted: Send,
  reviewed: CheckCircle2,
  closed: CheckSquare,
  compressor: Gauge,
  efficiency: TrendingUp,
  service: Wrench,
  task: ClipboardList,
  overdue: AlertTriangle,
  ppe: HardHat,
  contractor: HardHat,
  'admin-role': Users,
  eye: Eye,
  target: Target,
  flag: Flag,
  cart: ShoppingCart,
  package: Package,
  gauge: Gauge,
  activity: Activity,
  settings: Settings,
  percent: Percent,
  wrench: Wrench,
  zap: Zap,
  building: Building2,
  normalize: Sparkles,
  'export-roster': Award,
  today: CalendarDays,
  week: Layers,
  month: Calendar,
  draft: FileText,
  safe: Eye,
  unsafe: AlertTriangle,
  'high-risk': AlertTriangle,
  mechanical: Wrench,
  electrical: Zap,
  general: Building2,
  operational: Activity,
};
