/** Classic glyph map — existing Phosphor aliases already used by Studio glass. */

import type { ElementType } from 'react';
import type { IconMeaning } from '../shared/icon-meanings';
import {
  Activity, AlertOctagon, AlertTriangle, Archive, ArrowLeft, ArrowUpDown, ArrowsLeftRight,
  ArrowUUpLeft, ArrowUUpRight, Award,
  BarChart3, Bell, Briefcase, Building2, Calendar, Car, ChatCircleText, Check, CheckCircle2,
  ClipboardList, Clock, ClockCounterClockwise, DotsSixVertical, DollarSign, Download, Eye, EyeSlash,
  FilePdf, FileSpreadsheet,
  FileText, Filter, Flag, Gauge, GraduationCap, HardDrive, HardHat,
  HeartHandshake, House, ImageSquare, LayoutGrid, Layers, List,
  MagnifyingGlassMinus, MagnifyingGlassPlus, Package, Paperclip, Percent, PencilSimple, Pin, Plus,
  RefreshCw, SearchIcon, Settings, ShieldCheck, ShoppingCart, Sparkles,
  Star, Table2, Target, TextAa, Toolbox, Trash2, TreeStructure, TrendingUp,
  UploadSimple, UserCheck, UserGear, Users, Wrench, Zap,
  Pencil, CalendarDays, Hash, Send, CheckSquare, XCircle, Mail, Phone,
} from '../icons';

export const CLASSIC_ICONS: Record<IconMeaning, ElementType> = {
  employees: Users,
  artisans: HardHat,
  'nec-staff': Briefcase,
  'salaried-staff': Briefcase,
  'permanent-staff': UserCheck,
  'grid-view': LayoutGrid,
  'list-view': List,
  'table-view': Table2,
  'sheet-view': FileSpreadsheet,
  search: SearchIcon,
  filter: Filter,
  sort: ArrowUpDown,
  edit: Pencil,
  mail: Mail,
  phone: Phone,
  archive: Archive,
  analytics: BarChart3,
  refresh: RefreshCw,
  download: Download,
  plus: Plus,
  close: XCircle,
  warning: AlertTriangle,
  success: CheckCircle2,
  danger: Trash2,
  clock: Clock,
  calendar: Calendar,
  check: Check,
  pending: Clock,
  active: CheckCircle2,
  inactive: AlertTriangle,
  equipment: Gauge,
  maintenance: Settings,
  breakdown: AlertTriangle,
  availability: Percent,
  documents: FileText,
  storage: HardDrive,
  starred: Star,
  spares: Package,
  value: DollarSign,
  'out-of-stock': AlertOctagon,
  'low-stock': AlertTriangle,
  categories: BarChart3,
  drivers: Car,
  departments: Building2,
  requisition: ShoppingCart,
  cost: DollarSign,
  critical: Flag,
  notice: FileText,
  pinned: Pin,
  expired: Clock,
  training: GraduationCap,
  compliance: ShieldCheck,
  valid: CheckCircle2,
  'due-soon': Calendar,
  issues: Hash,
  recipients: Users,
  care: HeartHandshake,
  submitted: Send,
  reviewed: CheckCircle2,
  closed: CheckSquare,
  compressor: Gauge,
  efficiency: TrendingUp,
  service: Wrench,
  task: ClipboardList,
  overdue: AlertTriangle,
  ppe: HardHat,
  contractor: HardHat,
  'admin-role': Users,
  eye: Eye,
  target: Target,
  flag: Flag,
  cart: ShoppingCart,
  package: Package,
  gauge: Gauge,
  activity: Activity,
  settings: Settings,
  percent: Percent,
  wrench: Wrench,
  zap: Zap,
  building: Building2,
  normalize: Sparkles,
  'export-roster': Award,
  today: CalendarDays,
  week: Layers,
  month: Calendar,
  draft: FileText,
  safe: Eye,
  unsafe: AlertTriangle,
  'high-risk': AlertTriangle,
  mechanical: Wrench,
  electrical: Zap,
  general: Building2,
  operational: Activity,
  home: House,
  chat: ChatCircleText,
  bell: Bell,
  history: ClockCounterClockwise,
  pin: Pin,
  back: ArrowLeft,
  swap: ArrowsLeftRight,
  undo: ArrowUUpLeft,
  redo: ArrowUUpRight,
  attachment: Paperclip,
  image: ImageSquare,
  pdf: FilePdf,
  upload: UploadSimple,
  show: Eye,
  hide: EyeSlash,
  department: TreeStructure,
  font: TextAa,
  grip: DotsSixVertical,
  'zoom-in': MagnifyingGlassPlus,
  'zoom-out': MagnifyingGlassMinus,
  accounts: UserGear,
  app: Toolbox,
};
