/**
 * Source of the MyOffice service worker, as a string, so each deployment ships a different file.
 *
 * Why a generated file and not `public/sw.js`: browsers only treat a service worker as updated when its bytes
 * change. A static file never changes between deployments, so an installed app would never be told a newer build
 * exists. `buildServiceWorkerSource(buildId)` stamps the build id into the file; the route `app/sw.js/route.ts`
 * serves it with `Cache-Control: no-cache`, so every deployment is a detectable update.
 *
 * The worker's policy, in full (the unit test in `serviceWorkerSource.test.ts` evaluates this string and asserts it):
 * - It never intercepts navigations, `/api/**`, Supabase, any cross-origin request, any non-GET request or any
 *   Next.js build asset. Documents and data always come from the network, so a reopened or navigated app receives
 *   the newest deployed code, and no account-specific record is ever written to Cache Storage.
 * - The only thing it caches is the static icon set (`/icons/*.png`), network-first with the cache as an offline
 *   fallback. Icons are not account data. The manifest is not cached by the worker.
 * - It does **not** call `skipWaiting()` on install. A new worker waits until the app (or its tabs) is reopened, or
 *   until the page sends `{ type: 'SKIP_WAITING' }` after the user chooses to reload. An app that is already open is
 *   never refreshed under the user.
 * - On activation it removes caches from older worker versions and claims open clients (claiming does not reload them).
 */
export function buildServiceWorkerSource(buildId: string): string {
  const safeId = buildId.replace(/[^A-Za-z0-9._-]/g, '').slice(0, 64) || 'dev';
  return `// MyOffice service worker. Build: ${safeId}
// Generated by lib/serviceWorkerSource.ts; the build stamp makes every deployment a detectable update.
const BUILD_ID = ${JSON.stringify(safeId)};
const ICON_CACHE = 'myoffice-icons-v3';

self.addEventListener('install', () => {
  // Deliberately no skipWaiting(): an open app must not be refreshed or changed under the user.
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
  if (event.data && event.data.type === 'GET_BUILD_ID' && event.source) event.source.postMessage({ type: 'BUILD_ID', buildId: BUILD_ID });
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(key => key !== ICON_CACHE).map(key => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  const isIcon = url.origin === self.location.origin && /^\\/icons\\/[^/]+\\.png$/.test(url.pathname);
  // Everything else (navigations, API calls, Supabase, build assets, writes, cross-origin) is left to the network.
  if (request.method !== 'GET' || request.mode === 'navigate' || !isIcon) return;

  event.respondWith(
    fetch(request)
      .then(response => {
        if (response.ok) { const copy = response.clone(); caches.open(ICON_CACHE).then(cache => cache.put(request, copy)); }
        return response;
      })
      .catch(() => caches.match(request).then(cached => cached || Response.error())),
  );
});
`;
}
