'use client';

import { useState, type FormEvent } from 'react';
import { AnimatedSelect } from './AnimatedSelect';
import { ToolsIcon as Icon } from './ToolsIcon';
import { ToolsDateInput } from './ToolsDateInput';
import type { GatePass } from './complianceTypes';
import { departmentOf, type Tool, type WorkspaceAccount } from './prototype';
import s from './tools.module.css';

const ROLE_LABELS={hos:'Head of Section',hod:'Head of Department',security:'Security',finance:'Finance',general_manager:'General Manager'} as const;

export function ToolsGatePasses({passes,tools,departments,account,canCreate,onCreate,onDecide,onSetPin,onDownload}:{passes:GatePass[];tools:Tool[];departments:string[];account:WorkspaceAccount;canCreate:boolean;onCreate:(value:{movement_scope:'internal'|'external';department:string;destination:string;purpose:string;expected_out_at:string;expected_return_at?:string;finance_required:boolean;tool_ids:string[];notes?:string})=>Promise<void>;onDecide:(id:string,decision:'approve'|'reject',credential:string,comment?:string)=>Promise<void>;onSetPin:(password:string,pin:string)=>Promise<void>;onDownload:(gatePass:GatePass)=>Promise<void>}) {
  const [scope,setScope]=useState<'internal'|'external'>('external');const [department,setDepartment]=useState(account.department||departments[0]||'Engineering');const [destination,setDestination]=useState('');const [purpose,setPurpose]=useState('');const [outAt,setOutAt]=useState('');const [returnAt,setReturnAt]=useState('');const [financeRequired,setFinanceRequired]=useState(false);const [selectedTools,setSelectedTools]=useState<string[]>([]);const [notes,setNotes]=useState('');
  const [credential,setCredential]=useState('');const [comment,setComment]=useState('');const [password,setPassword]=useState('');const [pin,setPin]=useState('');
  const availableTools=tools.filter(tool=>!tool.archived&&tool.status!=='attention'&&departmentOf(tool)===department&&tool.backendId);
  const nextForAccount=(gatePass:GatePass)=>{const next=gatePass.approvals.find(item=>item.status==='pending');return next&&(account.approvalRoles||[]).includes(next.role)?next:undefined;};
  async function submit(event:FormEvent){event.preventDefault();await onCreate({movement_scope:scope,department,destination:destination.trim(),purpose:purpose.trim(),expected_out_at:new Date(outAt).toISOString(),expected_return_at:returnAt?new Date(returnAt).toISOString():undefined,finance_required:scope==='external'&&financeRequired,tool_ids:selectedTools,notes:notes||undefined});setDestination('');setPurpose('');setOutAt('');setReturnAt('');setSelectedTools([]);setNotes('');}
  return <div className={s.complianceGrid}>
    <section className={`${s.accountAccess} ${s.accountAccessDashboard}`}><div className={s.accountAccessHeader}><div><h2>Gate pass control</h2><p>Internal movement requires HOS approval. External movement follows HOS, HOD, Security, optional Finance, then General Manager.</p></div><div className={s.accountAccessSummary}><span><strong>{passes.filter(item=>item.status==='pending').length}</strong>Pending</span><span><strong>{passes.filter(item=>item.status==='approved').length}</strong>Approved</span><span><strong>{passes.length}</strong>Total</span></div></div>
      {!account.signingPinConfigured?<form className={s.pinSetup} onSubmit={async event=>{event.preventDefault();await onSetPin(password,pin);setPassword('');setPin('');}}><div><strong>Set a signing PIN</strong><small>Approvals always require your account password or this private PIN.</small></div><input aria-label="Current account password" type="password" minLength={6} required value={password} onChange={event=>setPassword(event.target.value)} placeholder="Current password"/><input aria-label="New signing PIN" type="password" inputMode="numeric" pattern="\d{4,12}" required value={pin} onChange={event=>setPin(event.target.value)} placeholder="4–12 digit PIN"/><button className={s.secondary} type="submit">Set PIN</button></form>:<div className={s.formContext}><Icon name="check"/><span><strong>Signing PIN configured</strong><small>Your password also remains valid for approval.</small></span></div>}
    </section>
    {canCreate&&<form className={`${s.form} ${s.formSection}`} onSubmit={submit}><div className={s.fieldHeading}><strong>New gate pass</strong><span>The system assigns the pass number</span></div><div className={s.formColumns}><div className={s.field}><label htmlFor="gate-scope">Movement scope</label><AnimatedSelect id="gate-scope" ariaLabel="Movement scope" value={scope} onChange={value=>setScope(value as typeof scope)} options={[{value:'internal',label:'Within mine premises'},{value:'external',label:'Outside mine premises'}]}/></div><div className={s.field}><label htmlFor="gate-department">Department</label><AnimatedSelect id="gate-department" ariaLabel="Gate pass department" value={department} onChange={value=>{setDepartment(value);setSelectedTools([]);}} options={departments.map(value=>({value,label:value}))}/></div><div className={s.field}><label htmlFor="gate-destination">Destination</label><input id="gate-destination" required value={destination} onChange={event=>setDestination(event.target.value)} placeholder="Workshop, contractor or destination"/></div><div className={s.field}><label htmlFor="gate-purpose">Purpose</label><input id="gate-purpose" required value={purpose} onChange={event=>setPurpose(event.target.value)} placeholder="Repair, calibration, transfer…"/></div><div className={s.field}><label htmlFor="gate-out">Expected departure</label><ToolsDateInput id="gate-out" type="datetime-local" required value={outAt} onChange={event=>setOutAt(event.target.value)}/></div><div className={s.field}><label htmlFor="gate-return">Expected return <small>Optional</small></label><ToolsDateInput id="gate-return" type="datetime-local" value={returnAt} onChange={event=>setReturnAt(event.target.value)}/></div></div><fieldset className={s.toolChecklist}><legend>Equipment on this pass</legend>{availableTools.map(tool=><label key={tool.id}><input type="checkbox" checked={selectedTools.includes(tool.backendId!)} onChange={event=>setSelectedTools(current=>event.target.checked?[...current,tool.backendId!]:current.filter(id=>id!==tool.backendId))}/><span><strong>{tool.id}</strong><small>{tool.name} · {tool.location}</small></span></label>)}{!availableTools.length&&<p className={s.formHint}>No movable equipment is available in this department.</p>}</fieldset>{scope==='external'&&<label className={s.checkRow}><input type="checkbox" checked={financeRequired} onChange={event=>setFinanceRequired(event.target.checked)}/><span><strong>Finance approval required</strong><small>Use for financially material movements or where departmental controls require Finance review.</small></span></label>}<div className={s.field}><label htmlFor="gate-notes">Movement notes <small>Optional</small></label><textarea id="gate-notes" rows={2} value={notes} onChange={event=>setNotes(event.target.value)}/></div><div className={s.formFooter}><button className={s.primary} disabled={!selectedTools.length||!outAt} type="submit">Create gate pass</button></div></form>}
    <section className={`${s.accountAccess} ${s.accountAccessDashboard}`}><div className={s.accountAccessHeader}><div><h2>Gate pass register</h2><p>Every signature is time-stamped, attributed and unlocked with a password or signing PIN.</p></div></div><div className={s.gatePassList}>{passes.map(gatePass=>{const next=gatePass.approvals.find(item=>item.status==='pending');const maySign=nextForAccount(gatePass);return <article key={gatePass.id} className={s.gatePassCard} data-status={gatePass.status}><header><div><strong>{gatePass.pass_number}</strong><small>{gatePass.movement_scope==='external'?'Outside mine premises':'Within mine premises'} · {gatePass.department}</small></div><span>{gatePass.status}</span></header><p><b>{gatePass.destination}</b> — {gatePass.purpose}</p><div className={s.complianceTags}>{gatePass.tools.map(tool=><span key={tool.id}>{tool.register_number}</span>)}</div><ol className={s.approvalSteps}>{gatePass.approvals.map(item=><li key={item.id} data-status={item.status}><i>{item.status==='approved'?'✓':item.status==='rejected'?'×':item.step_order}</i><span><strong>{ROLE_LABELS[item.role]}</strong><small>{item.signer_name?`${item.signer_name} · ${new Date(item.signed_at!).toLocaleString()}`:item.status==='pending'&&item.id===next?.id?'Awaiting signature':'Waiting for earlier approval'}</small></span></li>)}</ol>{maySign&&<div className={s.signingPanel}><div className={s.field}><label htmlFor={`credential-${gatePass.id}`}>Password or signing PIN</label><input id={`credential-${gatePass.id}`} type="password" value={credential} onChange={event=>setCredential(event.target.value)}/></div><div className={s.field}><label htmlFor={`comment-${gatePass.id}`}>Approval comment <small>Optional</small></label><input id={`comment-${gatePass.id}`} value={comment} onChange={event=>setComment(event.target.value)}/></div><button className={s.primary} disabled={!credential} onClick={async()=>{await onDecide(gatePass.id,'approve',credential,comment);setCredential('');setComment('');}}>Sign and approve</button><button className={s.secondary} disabled={!credential} onClick={async()=>{await onDecide(gatePass.id,'reject',credential,comment);setCredential('');setComment('');}}>Reject</button></div>}{gatePass.status==='approved'&&<div className={s.detailActions}><button className={s.primary} onClick={()=>onDownload(gatePass)}><Icon name="pdf"/>Download signed PDF</button><span className={s.formHint}>Verification code {gatePass.verification_code}</span></div>}</article>;})}{!passes.length&&<div className={s.empty}><Icon name="pdf" size={30}/><h2>No gate passes yet</h2><p>Create one when equipment needs controlled movement.</p></div>}</div></section>
  </div>;
}
