'use client';
import { type Dispatch, type SetStateAction } from 'react';
import { ToolsIcon as Icon } from './ToolsIcon';
import { type EquipmentIconFamily, type FontChoice, type FontSizeChoice, Help } from './ToolsUI';
import { AnimatedSelect } from './AnimatedSelect';
import s from './tools.module.css';
export type SectionName = 'overview' | 'register';
export type WorkspaceOptions = { order: SectionName[]; hidden: SectionName[]; font: FontChoice; fontSize: FontSizeChoice; equipmentIcons: EquipmentIconFamily; guidance: boolean; guide: boolean };
export const DEFAULT_OPTIONS: WorkspaceOptions = { order: ['overview', 'register'], hidden: [], font: 'inter', fontSize: 100, equipmentIcons: 'technical', guidance: true, guide: true };
const labels: Record<SectionName, string> = { overview: 'Quick overview', register: 'Tool register' };
export function ToolsCustomize({ options, setOptions }: { options: WorkspaceOptions; setOptions: Dispatch<SetStateAction<WorkspaceOptions>> }) {
  function move(index: number, delta: number) {
    setOptions(previous => { const order = [...previous.order]; [order[index], order[index + delta]] = [order[index + delta], order[index]]; return { ...previous, order }; });
  }
  return <div className={s.customize}>
    <div><div className={s.fieldHeading}><strong>Typography</strong><Help label="Typography">Choose the typeface that feels clearest to you. This changes Tools only.</Help></div><div className={s.fontChoices}>{(['inter', 'manrope', 'jakarta'] as const).map(font => <button key={font} data-font={font} aria-pressed={options.font === font} onClick={() => setOptions(p => ({ ...p, font }))}><span>Aa</span><strong>{font === 'jakarta' ? 'Plus Jakarta Sans' : font === 'inter' ? 'Inter' : 'Manrope'}</strong><small>{font === 'inter' ? 'Clear & precise' : font === 'manrope' ? 'Soft & open' : 'Modern & warm'}</small>{options.font === font && <Icon name="check" size={14} />}</button>)}</div></div>
    <div><div className={s.fieldHeading}><strong>Text size</strong><Help label="Text size">Choose any size from 85% to 130%. This changes the standalone Tools workspace only.</Help></div><div className={s.fontSizeRange}><input aria-label="Text size percentage" type="range" min="85" max="130" step="5" value={options.fontSize} onChange={event=>setOptions(previous=>({...previous,fontSize:Number(event.target.value)}))}/><output>{options.fontSize}%</output></div><div className={s.rangeLabels}><span>Compact</span><button type="button" onClick={()=>setOptions(previous=>({...previous,fontSize:100}))}>Reset to 100%</button><span>Larger</span></div></div>
    <div><div className={s.fieldHeading}><strong>Equipment icon family</strong><Help label="Equipment icons">Precision Line is the default because each silhouette closely represents its machine. Established icon families remain available and use the precision drawings where their own symbol is too generic. Uploaded photographs continue to take priority.</Help></div><div className={s.customizeSelect}><AnimatedSelect ariaLabel="Equipment icon family" value={options.equipmentIcons} onChange={value=>setOptions(previous=>({...previous,equipmentIcons:value as EquipmentIconFamily}))} options={[{value:'technical',label:'Precision Line · default'},{value:'tabler',label:'Tabler Outline'},{value:'iconoir',label:'Iconoir'},{value:'myoffice',label:'MyOffice Family'}]}/></div><p className={s.formHint}>Changes appear immediately in both grid and list views.</p></div>
    <div><div className={s.fieldHeading}><strong>Your workspace</strong><Help label="Workspace layout">Move sections up or down. Hide optional sections and restore them here whenever you need them.</Help></div><p className={s.formHint}>Keep what helps. Put it where you need it.</p><div className={s.layoutRows}>{options.order.map((section, index) => <div key={section} className={s.layoutRow}><Icon name="grip" size={18} /><span>{labels[section]}<small>{section === 'register' ? 'Always available' : options.hidden.includes(section) ? 'Hidden' : 'Visible'}</small></span><button aria-label={`Move ${labels[section]} up`} disabled={index === 0} className={s.iconButton} onClick={() => move(index, -1)}><Icon name="up" size={16} /></button><button aria-label={`Move ${labels[section]} down`} disabled={index === options.order.length - 1} className={s.iconButton} onClick={() => move(index, 1)}><Icon name="moveDown" size={16} /></button>{section !== 'register' && <button className={s.iconButton} aria-label={`${options.hidden.includes(section) ? 'Show' : 'Hide'} ${labels[section]}`} onClick={() => setOptions(p => ({ ...p, hidden: p.hidden.includes(section) ? p.hidden.filter(item => item !== section) : [...p.hidden, section] }))}><Icon name={options.hidden.includes(section) ? 'show' : 'hide'} size={17} /></button>}</div>)}</div></div>
    <label className={s.toggleRow}><span><strong>Helpful hints</strong><small>Show guidance on hover, focus or tap.</small></span><input aria-label="Helpful hints" type="checkbox" checked={options.guidance} onChange={e => setOptions(p => ({ ...p, guidance: e.target.checked }))} /></label>
    <button className={s.secondary} onClick={() => setOptions({ ...DEFAULT_OPTIONS, order: [...DEFAULT_OPTIONS.order], hidden: [] })}><Icon name="reset" size={16} />Restore default layout</button><p className={s.demoNote}>Your layout and appearance choices are saved on this device.</p>
  </div>;
}
