'use client';

import { useState, type FormEvent } from 'react';
import { ToolsIcon as Icon } from './ToolsIcon';
import type { WorkspaceAccount } from './prototype';
import s from './tools.module.css';

export function ToolsAuth({ accounts, currentAccount, onCreate, onLogin, onLogout, onCancel }: { accounts: WorkspaceAccount[]; currentAccount: WorkspaceAccount | null; onCreate: (account: WorkspaceAccount) => void | Promise<void>; onLogin: (username: string, password: string) => boolean | Promise<boolean>; onLogout: () => void; onCancel: () => void }) {
  const [mode,setMode]=useState<'login'|'create'>('login'); const [name,setName]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [canIssue,setCanIssue]=useState(false); const [error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setError('');if(mode==='login'){if(!await onLogin(username,password))setError('The username or password does not match.');return;}if(accounts.some(account=>account.username.toLowerCase()===username.trim().toLowerCase())){setError('That username is already in use.');return;}await onCreate({id:crypto.randomUUID(),name:name.trim(),username:username.trim().toLowerCase(),password,canIssue});}
  if (currentAccount) return <div className={s.form}><div className={s.formContext}><Icon name="user" size={19}/><span><strong>Signed in as {currentAccount.name}</strong><small>{currentAccount.username} · {currentAccount.canIssue?'Equipment administrator':'View-only account'}</small></span></div><p className={s.formHint}>This device will keep you signed in until the seven-day session expires or you sign out.</p><div className={s.formFooter}><button type="button" className={s.secondary} onClick={onCancel}>Close</button><button type="button" className={s.secondary} onClick={onLogout}>Sign out</button></div></div>;
  return <form className={s.form} onSubmit={submit}><div className={s.authMode}><button type="button" aria-pressed={mode==='login'} onClick={()=>{setMode('login');setError('');}}>Sign in</button><button type="button" aria-pressed={mode==='create'} onClick={()=>{setMode('create');setError('');}}>Create account</button></div>{mode==='create'&&<div className={s.field}><label htmlFor="account-name">Your name</label><input id="account-name" aria-label="Your name" required minLength={2} value={name} onChange={event=>setName(event.target.value)} autoComplete="name"/></div>}<div className={s.field}><label htmlFor="account-username">Username or email</label><input id="account-username" aria-label="Username or email" required minLength={3} value={username} onChange={event=>setUsername(event.target.value)} autoComplete="username"/></div><div className={s.field}><label htmlFor="account-password">Password</label><input id="account-password" aria-label="Password" required minLength={6} type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></div>{mode==='create'&&<label className={s.toggleRow}><span><strong>Equipment administrator</strong><small>Admins can issue, receive and manage equipment records. Other accounts have view-only access.</small></span><input type="checkbox" aria-label="Equipment administrator" checked={canIssue} onChange={event=>setCanIssue(event.target.checked)}/></label>}{error&&<p className={s.warning} role="alert">{error}</p>}<p className={s.formHint}>Your password is verified by the backend and is never stored in this browser.</p><div className={s.formFooter}><button type="button" className={s.secondary} onClick={onCancel}>Cancel</button><button type="submit" className={s.primary}>{mode==='login'?'Sign in':'Create account'}<Icon name="arrow" size={16}/></button></div></form>;
}
