'use client';

import { useState, type FormEvent } from 'react';
import { ToolsIcon as Icon } from './ToolsIcon';
import { AnimatedSelect } from './AnimatedSelect';
import type { AccountRole, WorkspaceAccount } from './prototype';
import s from './tools.module.css';

function AccountAccessRow({account,departments,onUpdate}:{account:WorkspaceAccount;departments:string[];onUpdate:(id:string,role:AccountRole,department?:string)=>void}) {
  const [role,setRole]=useState<AccountRole>(account.role);const [department,setDepartment]=useState(account.department||departments[0]||'Engineering');
  return <div className={s.accountAccessRow}><div><strong>{account.name}</strong><small>{account.username}</small></div><AnimatedSelect ariaLabel={`Role for ${account.name}`} value={role} onChange={value=>setRole(value as AccountRole)} options={[{value:'viewer',label:'Viewer · read only'},{value:'issuer',label:'Issuer · record movements'},{value:'admin',label:'Admin · manage system'}]}/>{role==='issuer'&&<AnimatedSelect ariaLabel={`Department for ${account.name}`} value={department} onChange={setDepartment} options={departments.map(value=>({value,label:value}))}/>}<div className={s.accountAccessActions}><button type="button" className={s.secondary} onClick={()=>onUpdate(account.id,role,role==='issuer'?department:undefined)}>Apply access</button>{account.role==='issuer'&&<button type="button" className={s.textButton} onClick={()=>{setRole('viewer');void onUpdate(account.id,'viewer');}}>Revoke issuing</button>}</div></div>;
}

export function ToolsAccountAccess({accounts,departments,onUpdateRole}:{accounts:WorkspaceAccount[];departments:string[];onUpdateRole:(id:string,role:AccountRole,department?:string)=>void|Promise<void>}) {
  const admins=accounts.filter(account=>account.role==='admin').length;const issuers=accounts.filter(account=>account.role==='issuer').length;const viewers=accounts.filter(account=>account.role==='viewer').length;
  return <section className={`${s.accountAccess} ${s.accountAccessDashboard}`}><div className={s.accountAccessHeader}><div><h2>Account access</h2><p>Grant or revoke access and assign each Issuer to one department.</p></div><div className={s.accountAccessSummary}><span><strong>{accounts.length}</strong>Accounts</span><span><strong>{admins}</strong>Admins</span><span><strong>{issuers}</strong>Issuers</span><span><strong>{viewers}</strong>Viewers</span></div></div><p className={s.formHint}>Everyone can view the operational register after signing in. Issuers record movements for their assigned department. Administrators manage accounts and system oversight.</p><div className={s.accountAccessList}>{accounts.map(account=><AccountAccessRow key={account.id} account={account} departments={departments} onUpdate={onUpdateRole}/>)}</div></section>;
}

export function ToolsAuth({ accounts, currentAccount, departments, onCreate, onLogin, onUpdateRole, onLogout, onCancel }: { accounts: WorkspaceAccount[]; currentAccount: WorkspaceAccount | null; departments:string[]; onCreate: (account: WorkspaceAccount) => void | Promise<void>; onLogin: (username: string, password: string) => boolean | Promise<boolean>; onUpdateRole:(id:string,role:AccountRole,department?:string)=>void|Promise<void>; onLogout: () => void; onCancel: () => void }) {
  const [mode,setMode]=useState<'login'|'create'>('login'); const [name,setName]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setError('');if(mode==='login'){if(!await onLogin(username,password))setError('The username or password does not match.');return;}if(accounts.some(account=>account.username.toLowerCase()===username.trim().toLowerCase())){setError('That username is already in use.');return;}await onCreate({id:crypto.randomUUID(),name:name.trim(),username:username.trim().toLowerCase(),password,role:'viewer',canIssue:false});}
  if (currentAccount) return <div className={s.form}><div className={s.formContext}><Icon name="user" size={19}/><span><strong>Signed in as {currentAccount.name}</strong><small>{currentAccount.username} · {currentAccount.role==='issuer'?`Issuer for ${currentAccount.department}`:currentAccount.role==='admin'?'Administrator':'View-only account'}</small></span></div>{currentAccount.role==='admin'&&<ToolsAccountAccess accounts={accounts} departments={departments} onUpdateRole={onUpdateRole}/>}<p className={s.formHint}>This device will keep you signed in until the seven-day session expires or you sign out.</p><div className={s.formFooter}><button type="button" className={s.secondary} onClick={onCancel}>Close</button><button type="button" className={s.secondary} onClick={onLogout}>Sign out</button></div></div>;
  return <form className={s.form} onSubmit={submit}><div className={s.authMode}><button type="button" aria-pressed={mode==='login'} onClick={()=>{setMode('login');setError('');}}>Sign in</button><button type="button" aria-pressed={mode==='create'} onClick={()=>{setMode('create');setError('');}}>Create account</button></div>{mode==='create'&&<div className={s.field}><label htmlFor="account-name">Your name</label><input id="account-name" aria-label="Your name" required minLength={2} value={name} onChange={event=>setName(event.target.value)} autoComplete="name"/></div>}<div className={s.field}><label htmlFor="account-username">Username or email</label><input id="account-username" aria-label="Username or email" required minLength={3} value={username} onChange={event=>setUsername(event.target.value)} autoComplete="username"/></div><div className={s.field}><label htmlFor="account-password">Password</label><input id="account-password" aria-label="Password" required minLength={6} type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></div>{mode==='create'&&<p className={s.formHint}>New accounts start as Viewers. An administrator can later grant department-specific Issuer access.</p>}{error&&<p className={s.warning} role="alert">{error}</p>}<p className={s.formHint}>Your password is verified by the backend and is never stored in this browser.</p><div className={s.formFooter}><button type="button" className={s.secondary} onClick={onCancel}>Cancel</button><button type="submit" className={s.primary}>{mode==='login'?'Sign in':'Create account'}<Icon name="arrow" size={16}/></button></div></form>;
}
