'use client';

import { useState } from 'react';
import { ToolsIcon as Icon } from './ToolsIcon';
import { ToolsDialog } from './ToolsUI';
import type { Employee, Tool } from './prototype';
import s from './tools.module.css';

export function ToolsPeople({ employees, tools, search, onAdd, onIssue }: { employees: Employee[]; tools: Tool[]; search: string; onAdd: () => void; onIssue: (employee:Employee) => void }) {
  const [selected,setSelected]=useState<Employee|null>(null);
  const query = search.trim().toLowerCase();
  const visible = employees.filter(employee => `${employee.name} ${employee.employeeNumber} ${employee.department} ${employee.jobTitle || ''}`.toLowerCase().includes(query));
  const held=selected?tools.filter(tool=>tool.holder===selected.name||tool.holder?.startsWith(`${selected.name} ·`)):[];
  if (!employees.length) return <div className={s.empty}><Icon name="user" size={32}/><h2>Build your employee register</h2><p>Add the people who may receive tools and equipment. This register is separate from MyOffice.</p><button className={s.primary} onClick={onAdd}><Icon name="plus" size={16}/>Add the first employee</button></div>;
  return <><div className={s.peopleRegister}>{visible.map(employee=><button type="button" key={employee.id} className={s.personCard} onClick={()=>setSelected(employee)} aria-label={`View ${employee.name}`}><span className={s.personAvatar}>{employee.name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()}</span><div><strong>{employee.name}</strong><small>{employee.employeeNumber} · {employee.department}</small>{employee.jobTitle&&<p>{employee.jobTitle}</p>}</div><span className={s.personState}>{employee.active?'Active':'Inactive'}</span><Icon name="chevron" size={16}/></button>)}{!visible.length&&<div className={s.empty}><Icon name="search" size={28}/><h2>No matching employees</h2><p>Try a name, employee number or department.</p></div>}</div><ToolsDialog open={!!selected} onClose={()=>setSelected(null)} title={selected?.name||'Employee details'} description={selected?`${selected.employeeNumber} · ${selected.department}`:''} wide>{selected&&<div className={s.employeeDetail}><div className={s.employeeIdentity}><span className={s.personAvatar}>{selected.name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()}</span><div><strong>{selected.jobTitle||'Job title not recorded'}</strong><p>{selected.active?'Active employee':'Inactive employee'} · {selected.department}</p></div></div><section><div className={s.fieldHeading}><h3>Currently assigned</h3><span>{held.length} {held.length===1?'item':'items'}</span></div>{held.length?<div className={s.employeeTools}>{held.map(tool=><div key={tool.id}><Icon name="box" size={16}/><span><strong>{tool.name}</strong><small>{tool.id} · {tool.location}</small></span></div>)}</div>:<p className={s.formHint}>No tools or equipment are currently assigned to this person.</p>}</section><div className={s.formFooter}><button className={s.secondary} onClick={()=>setSelected(null)}>Close</button><button className={s.primary} onClick={()=>{const employee=selected;setSelected(null);onIssue(employee);}}><Icon name="out" size={16}/>Issue a tool</button></div></div>}</ToolsDialog></>;
}
