'use client';

import { useEffect, useRef, useState } from 'react';
import { ToolsIcon as Icon } from './ToolsIcon';
import s from './tools.module.css';

export function ToolsFeedback({ onSubmit, onCancel }: { onSubmit: (text: string, audio?: Blob) => void; onCancel: () => void }) {
  const [text,setText]=useState(''); const [recording,setRecording]=useState(false); const [seconds,setSeconds]=useState(0); const [audio,setAudio]=useState<Blob>(); const [audioUrl,setAudioUrl]=useState(''); const [error,setError]=useState(''); const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
  useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl);},[audioUrl]);
  useEffect(()=>{if(!recording)return;const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer);},[recording]);
  function removeAudio(){setAudio(undefined);setAudioUrl('');}
  async function toggleRecording(){if(recording){recorder.current?.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];setSeconds(0);const next=new MediaRecorder(stream);recorder.current=next;next.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data);};next.onstop=()=>{const blob=new Blob(chunks.current,{type:next.mimeType||'audio/webm'});setAudio(blob);setAudioUrl(URL.createObjectURL(blob));setRecording(false);stream.getTracks().forEach(track=>track.stop());};next.start();setRecording(true);setError('');}catch{setError('Microphone access was not available. You can still send written feedback.');}}
  return <div className={s.form}><div className={s.field}><label htmlFor="tools-feedback">What should we improve?</label><textarea id="tools-feedback" aria-label="Feedback or suggestion" rows={5} value={text} onChange={event=>setText(event.target.value)} placeholder="Describe what you were trying to do, what felt difficult, or what would help…"/></div><div className={s.audioFeedback}><button type="button" className={recording?s.recordingButton:s.secondary} onClick={toggleRecording}><Icon name={recording?'alert':'attachment'} size={17}/>{recording?'Stop recording':'Record audio feedback'}</button>{audio&&!recording&&<span><Icon name="check" size={15}/>Audio ready · {Math.max(1,Math.round(audio.size/1024))} KB <button type="button" onClick={removeAudio}>Remove</button></span>}</div>{recording&&<div className={s.recordingVisual} role="status" aria-live="polite"><span className={s.recordingDot}/><strong>Recording</strong><div className={s.recordingWave} aria-hidden="true">{[0,1,2,3,4,5,6].map(bar=><i key={bar} style={{animationDelay:`${bar*.09}s`}}/>)}</div><time>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</time></div>}{audioUrl&&<div className={s.audioPreview}><strong>Review your recording</strong><audio controls preload="metadata" src={audioUrl} aria-label="Recorded feedback preview"><track kind="captions" srcLang="en" label="No captions available"/>Your browser does not support audio playback.</audio></div>}{error&&<p className={s.warning} role="alert">{error}</p>}<p className={s.formHint}>Play the recording before sending if you want to check it. Feedback is associated with the signed-in prototype account so the product team can follow the context.</p><div className={s.formFooter}><button type="button" className={s.secondary} onClick={onCancel}>Cancel</button><button type="button" className={s.primary} disabled={!text.trim()&&!audio} onClick={()=>onSubmit(text.trim(),audio)}>Send feedback<Icon name="arrow" size={16}/></button></div></div>;
}
