// app/spares/requisitionPdf.ts — the parts requisition as a one-page-per-24-lines landscape PDF: who asked, for what, how urgent, and
// every line with its quantity, unit price and total.
import { EXPORT_BRAND_RGB } from '@/lib/exportUtils';
import { formatCurrency } from '@/components/shared/utils';
import { filled, lineValue, requisitionTotal } from './stock';
import type { ReqHeader, ReqLine } from './types';
import { formatLongDate } from '@/lib/format';

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export async function downloadRequisitionPdf(header: ReqHeader, lines: ReqLine[]): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const today = formatLongDate(new Date());
  const rows = filled(lines);
  doc.setFillColor(...EXPORT_BRAND_RGB); doc.rect(0, 0, 297, 26, 'F');
  doc.setTextColor(255, 255, 255); doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.text('Ozech MyOffice', 12, 11);
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.text('SPARE PARTS MANAGEMENT', 12, 17);
  doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.text('Parts Requisition', 285, 11, { align: 'right' });
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.text(today, 285, 17, { align: 'right' });
  doc.setFillColor(235, 242, 248); doc.rect(0, 26, 297, 14, 'F');
  doc.setTextColor(...EXPORT_BRAND_RGB); doc.setFontSize(8); doc.setFont('helvetica', 'bold');
  const metaY = 33;
  const meta: [string, string][] = [['Requested By', header.requester || '-'], ['Required For', header.required_for || '-'], ['Urgency', cap(header.urgency)], ['Priority', cap(header.priority)]];
  meta.forEach(([label, value], i) => {
    const x = 12 + i * 70;
    doc.text(`${label}:`, x, metaY - 3); doc.setFont('helvetica', 'normal'); doc.setTextColor(26, 37, 51);
    doc.text(value, x, metaY + 2); doc.setFont('helvetica', 'bold'); doc.setTextColor(...EXPORT_BRAND_RGB);
  });
  if (header.reason) { doc.setFont('helvetica', 'bold'); doc.text('Reason:', 12, metaY + 8); doc.setFont('helvetica', 'normal'); doc.setTextColor(26, 37, 51); doc.text(header.reason.slice(0, 120), 38, metaY + 8); }
  autoTable(doc, {
    startY: header.reason ? 52 : 46,
    head: [['#', 'Stock Code', 'Description', 'UoM', 'Qty', 'Unit Price', 'Line Total']],
    body: rows.map((l, i) => [i + 1, l.spare!.stock_code, l.spare!.description, l.spare!.unit_of_measure || 'UN', l.qty, formatCurrency(l.spare!.unit_price), formatCurrency(lineValue(l.qty, l.spare!.unit_price))]),
    foot: [['', '', '', '', '', 'Grand Total', formatCurrency(requisitionTotal(lines))]],
    headStyles: { fillColor: EXPORT_BRAND_RGB, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    footStyles: { fillColor: [220, 231, 240], textColor: EXPORT_BRAND_RGB, fontStyle: 'bold', fontSize: 10 },
    bodyStyles: { fontSize: 9, textColor: [26, 37, 51] }, alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 0: { cellWidth: 10, halign: 'center' }, 1: { cellWidth: 34, fontStyle: 'bold' }, 2: { cellWidth: 'auto' }, 3: { cellWidth: 16, halign: 'center' }, 4: { cellWidth: 16, halign: 'center' }, 5: { cellWidth: 28, halign: 'right' }, 6: { cellWidth: 30, halign: 'right', fontStyle: 'bold' } },
    margin: { left: 12, right: 12 }, showFoot: 'lastPage',
  });
  const pages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) { doc.setPage(i); doc.setFontSize(8); doc.setTextColor(160, 160, 160); doc.text(`Generated by Ozech MyOffice, ${today}`, 12, 205); doc.text(`Page ${i} of ${pages}`, 285, 205, { align: 'right' }); }
  doc.save(`requisition-${new Date().toISOString().slice(0, 10)}.pdf`);
}
