// Glyph mapping layer — every icon in MyOffice is a Phosphor glyph re-exported
// under a stable logical name (the names call sites already use). Import icons
// from '@/components/ui-system', never from '@phosphor-icons/react' directly
// (enforced by ESLint). Weight comes from context: see Icon.tsx and README.
//
// To add a glyph, add one line here. Keep one glyph per meaning: edit → Pencil,
// delete → Trash2, add → Plus, call → Phone, settings → Settings (gear).

export type { Icon as PhosphorIcon, IconWeight } from '@phosphor-icons/react';
import type { ElementType } from 'react';

/** Any icon component accepted by an `icon={…}` prop. */
export type IconComponent = ElementType;
/** @deprecated name kept for call sites migrating from lucide; use IconComponent. */
export type LucideIcon = ElementType;

export {
  Pulse as Activity,
  Alarm as AlarmClock,
  WarningCircle as AlertCircle,
  WarningOctagon as AlertOctagon,
  Warning as AlertTriangle,
  TextAlignLeft as AlignLeft,
  AppleLogo as Apple,
  Archive,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowsDownUp as ArrowUpDown,
  ArrowUpRight,
  Medal as Award,
  Medal as AwardIcon,
  Baby,
  SealCheck as Badge,
  SealCheck as BadgeCheck,
  Prohibit as Ban,
  Money as Banknote,
  ChartBar as BarChart,
  ChartBar as BarChart2,
  ChartBar as BarChart3,
  Bathtub as Bath,
  Bed,
  Cow as Beef,
  BeerBottle as Beer,
  Bell,
  TextB as Bold,
  BookBookmark as BookHeart,
  BookmarkSimple as Bookmark,
  BookBookmark as BookMarked,
  BookOpen,
  Package as Box,
  Stack as Boxes,
  Brain,
  Briefcase,
  Briefcase as BriefcaseBusiness,
  PaintBrush as Brush,
  Buildings as Building,
  Buildings as Building2,
  Cake,
  Calculator,
  Calendar,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CalendarX as CalendarOff,
  CalendarBlank as CalendarRange,
  Camera,
  Car,
  Carrot,
  Cat,
  Check,
  Checks as CheckCheck,
  CheckCircle,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CheckSquare,
  CookingPot as ChefHat,
  CookingPot as ChefHatIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretDoubleDown as ChevronsDown,
  ArrowsInLineVertical as ChevronsDownUp,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleRight as ChevronsRight,
  CaretDoubleUp as ChevronsUp,
  ArrowsOutLineVertical as ChevronsUpDown,
  CaretUp as ChevronUp,
  CaretUp as ChevronUpIcon,
  Church,
  Circle,
  CheckCircle as CircleCheckIcon,
  CurrencyCircleDollar as CircleDollarSign,
  Circle as CircleIcon,
  ClipboardText as ClipboardCheck,
  ClipboardText as ClipboardList,
  Clipboard as ClipboardPlus,
  Clock,
  Clock as Clock3,
  Clock as Clock4,
  Cloud,
  CloudRain,
  Coffee,
  Coffee as CoffeeIcon,
  Gear as Cog,
  Coins,
  Columns,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  CreditCard as CreditCardIcon,
  Cross,
  Crown,
  Database,
  Diamond,
  Dog,
  CurrencyDollar as DollarSign,
  Door as DoorOpen,
  DownloadSimple as Download,
  CloudArrowDown as DownloadCloud,
  Drop as Droplet,
  Drop as Droplets,
  Cow as Drumstick,
  PencilSimple as Edit,
  PencilSimple as Edit2,
  PencilSimple as Edit3,
  Egg as EggFried,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FacebookLogo as Facebook,
  Factory,
  Fan,
  File,
  PresentationChart as FileBarChart,
  SealCheck as FileCheck,
  FileText as FileCheck2,
  FileArrowDown as FileDown,
  FileText as FileEdit,
  FileText as FilePieChart,
  FilePlus,
  FileMagnifyingGlass as FileSearch,
  FileText as FileSignature,
  FileXls as FileSpreadsheet,
  FileText,
  FileArrowUp as FileUp,
  IdentificationCard as FileUser,
  WarningDiamond as FileWarning,
  FilmSlate as Film,
  Funnel as Filter,
  FunnelX as FilterX,
  Fish,
  Flag,
  Flame,
  Flame as FlameIcon,
  Flashlight,
  Flask as FlaskConical,
  Flower,
  Folder,
  FolderOpen,
  FolderPlus,
  GasPump as Fuel,
  Gauge,
  Diamond as Gem,
  Gift,
  GitBranch,
  GitDiff as GitCompare,
  Globe,
  GraduationCap,
  GridFour as Grid,
  GridFour as Grid2X2,
  GridNine as Grid3x3,
  GridNine as Grid3X3,
  DotsSixVertical as GripVertical,
  Belt,
  Boot,
  BoxingGlove,
  Dress,
  FaceMask,
  Goggles,
  Hoodie,
  Pants,
  Seatbelt,
  ShirtFolded,
  Sneaker,
  HandCoins,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Heart,
  Handshake as HeartHandshake,
  Heartbeat as HeartPulse,
  Question as HelpCircle,
  Hexagon,
  ClockCounterClockwise as History,
  House as Home,
  IceCream,
  Image,
  Image as ImageIcon,
  Info,
  Info as InfoIcon,
  InstagramLogo as Instagram,
  TextItalic as Italic,
  Key,
  Bank as Landmark,
  Laptop,
  Stack as Layers,
  Layout,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Leaf,
  Books as Library,
  Lightbulb,
  ChartLine as LineChart,
  Link,
  Link as Link2,
  LinkedinLogo as Linkedin,
  List,
  TreeStructure as ListTree,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  Lock,
  SignIn as LogIn,
  SignOut as LogOut,
  Envelope as Mail,
  Mailbox,
  MapTrifold as Map,
  MapPin,
  MapPin as MapPinIcon,
  Martini,
  ArrowsOut as Maximize2,
  Megaphone,
  Memory as MemoryStick,
  List as Menu,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  ChatCenteredDots as MessageSquareWarning,
  Microphone as Mic,
  Drop as Milk,
  ArrowsIn as Minimize2,
  Minus,
  Monitor,
  Moon,
  DotsThree as MoreHorizontal,
  DotsThreeVertical as MoreVertical,
  ArrowsVertical as MoveVertical,
  MusicNote as Music,
  NavigationArrow as Navigation,
  Graph as Network,
  Newspaper,
  Octagon,
  XCircle as OctagonXIcon,
  Package,
  HandDeposit as PackageMinus,
  Package as PackageOpen,
  PaintBucket,
  Palette,
  SidebarSimple as PanelLeftClose,
  Sidebar as PanelLeftOpen,
  Paperclip,
  Confetti as PartyPopper,
  Pause,
  PauseCircle,
  PencilSimple as Pen,
  PencilSimple as Pencil,
  PencilSimpleLine as PenLine,
  PenNib as PenTool,
  Percent,
  DeviceMobile as Phone,
  PhoneCall,
  ChartPie as PieChart,
  PushPin as Pin,
  PushPinSlash as PinOff,
  Pizza,
  Play,
  PlayCircle,
  Plus,
  MicrophoneStage as Podcast,
  Power,
  Printer,
  Presentation as Projector,
  Quotes as Quote,
  Broadcast as Radar,
  Radio,
  Receipt,
  ArrowsClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  Repeat as Repeat2,
  ArrowCounterClockwise as RotateCcw,
  BowlFood as Salad,
  Hamburger as Sandwich,
  FloppyDisk as Save,
  Scales as Scale,
  Scan,
  ChartScatter as ScatterChart,
  Scissors,
  MagnifyingGlass as Search,
  MagnifyingGlass as SearchIcon,
  PaperPlaneTilt as Send,
  HardDrives as Server,
  Gear as Settings,
  GearSix as Settings2,
  ShareNetwork as Share2,
  Spiral as Shell,
  Shield,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  Shield as ShieldIcon,
  TShirt as Shirt,
  ShoppingBag,
  Basket as ShoppingBasket,
  ShoppingCart,
  Signature,
  FadersHorizontal as SlidersHorizontal,
  DeviceMobile as Smartphone,
  Smiley as Smile,
  Snowflake,
  SortAscending as SortAsc,
  SortDescending as SortDesc,
  BowlFood as Soup,
  Sparkle,
  Sparkle as Sparkles,
  SpeakerHigh as Speaker,
  Square,
  Star,
  Stethoscope,
  Storefront as Store,
  Storefront as StoreIcon,
  Sun,
  SunHorizon as Sunrise,
  SunHorizon as Sunset,
  Table,
  Table as Table2,
  DeviceTablet as Tablet,
  Tag,
  Target,
  TextT as TextCursor,
  Thermometer,
  Thermometer as ThermometerSun,
  ThumbsUp,
  Timer,
  Toolbox as ToolCase,
  Tractor,
  Trash,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Triangle,
  Warning as TriangleAlertIcon,
  Trophy,
  Truck,
  Truck as TruckIcon,
  Television as Tv,
  TwitterLogo as Twitter,
  TextT as Type,
  Umbrella,
  LockOpen as Unlock,
  UploadSimple as Upload,
  CloudArrowUp as UploadCloud,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  User as UserRound,
  Users,
  Users as UsersRound,
  UserMinus as UserX,
  ForkKnife as Utensils,
  ForkKnife as UtensilsCrossed,
  VideoCamera as Video,
  SpeakerHigh as Volume2,
  Wallet,
  MagicWand as Wand2,
  Warehouse,
  Watch,
  Waves,
  Plant as Wheat,
  WifiHigh as Wifi,
  Wind,
  Wine,
  Wine as WineIcon,
  FlowArrow as Workflow,
  Wrench,
  X,
  XCircle,
  X as XIcon,
  YoutubeLogo as Youtube,
  Lightning as Zap,
  LightningSlash as ZapOff,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
  CircleHalf as IconStyleGlyph,
  BatteryCharging,
  ChartLineUp,
  DownloadSimple,
  HouseLine,
  IdentificationCard,
  Kanban,
  ListChecks as ListTodo,
  QrCode,
  Rocket,
  SquaresFour,
  TextAa,
  Wrench as Tool,
  ArrowsDownUp,
  ArrowsLeftRight,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowUp,
  ArrowUUpLeft,
  ArrowUUpRight,
  Buildings,
  CalendarBlank,
  CaretDown,
  CaretRight,
  ChatCircleText,
  CirclesFour,
  ClipboardText,
  ClockCounterClockwise,
  Cube,
  CurrencyCircleDollar,
  DotsSixVertical,
  DotsThree,
  EnvelopeSimple,
  EyeSlash,
  FilePdf,
  FileXls,
  Gear,
  Handshake,
  HardDrives,
  House,
  ImageSquare,
  Lightning,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  Medal,
  PaperPlaneTilt,
  PencilSimple,
  Pulse,
  Rows,
  Toolbox,
  TreeStructure,
  TrendUp,
  UploadSimple,
  UserGear,
  Warning,
  WarningCircle,
  WarningOctagon,
} from '@phosphor-icons/react';
export {
  ArrowSquareOut,
  ArrowsClockwise,
  CaretLeft,
  CaretUp,
  DotsThreeVertical,
  FloppyDisk,
  Funnel,
  Microphone,
  Prohibit,
  Question,
  SidebarSimple,
  SignIn,
  SignOut,
} from '@phosphor-icons/react';
