// Semantic icon meanings. Interface code asks for a MEANING; this file is the only
// place that decides which Phosphor glyph a meaning uses — one glyph per meaning,
// so "edit" looks the same on every page. Contextual weights live in Icon.tsx.

import type { ElementType } from 'react';
import {
  Archive, ArrowClockwise, ArrowCounterClockwise, ArrowDown, ArrowLeft, ArrowSquareOut, ArrowUUpLeft, ArrowUUpRight,
  ArrowUp, ArrowsClockwise, ArrowsDownUp, ArrowsLeftRight, Bell, Buildings, CalendarBlank, Camera,
  Car, CaretDown, CaretLeft, CaretRight, CaretUp, ChartLineUp, ChatCircleText, Check,
  CheckCircle, CheckSquare, CirclesFour, ClipboardText, Clock, ClockCounterClockwise, Columns, Copy,
  Cube, CurrencyCircleDollar, DotsSixVertical, DotsThree, DotsThreeVertical, DownloadSimple, EnvelopeSimple, Eye,
  EyeSlash, File, FilePdf, FileXls, Flag, FloppyDisk, Funnel, Gauge,
  Gear, GraduationCap, Handshake, HardDrives, HardHat, Hash, Heart, House,
  IdentificationCard, ImageSquare, Info, Key, Lightning, Link, List, Lock,
  MagnifyingGlass, MagnifyingGlassMinus, MagnifyingGlassPlus, MapPin, Medal, Microphone, Package, PaperPlaneTilt,
  Paperclip, PencilSimple, Percent, Phone, Plus, Printer, Prohibit, Pulse,
  Question, Rows, ShieldCheck, ShoppingCart, SidebarSimple, SignIn, SignOut, SlidersHorizontal,
  Sparkle, SquaresFour, Star, Table, Target, TextAa, Toolbox, Trash,
  TreeStructure, TrendUp, UploadSimple, User, UserCheck, UserGear, Users, Warning,
  WarningOctagon, Wrench, X, XCircle,
} from './glyphs';

export const ICON_MEANINGS = [
  'employees', 'artisans', 'nec-staff', 'salaried-staff', 'permanent-staff',
  'grid-view', 'list-view', 'table-view', 'sheet-view',
  'search', 'filter', 'sort', 'edit', 'mail', 'phone', 'archive', 'analytics',
  'refresh', 'download', 'plus', 'close', 'warning', 'success', 'danger',
  'clock', 'calendar', 'check', 'pending', 'active', 'inactive',
  'equipment', 'maintenance', 'breakdown', 'availability',
  'documents', 'storage', 'starred',
  'spares', 'value', 'out-of-stock', 'low-stock', 'categories',
  'drivers', 'departments',
  'requisition', 'cost', 'critical',
  'notice', 'pinned', 'expired',
  'training', 'compliance', 'valid', 'due-soon',
  'issues', 'recipients',
  'care', 'submitted', 'reviewed', 'closed',
  'compressor', 'efficiency', 'service',
  'task', 'overdue',
  'ppe', 'contractor',
  'admin-role',
  'eye', 'target', 'flag', 'cart', 'package',
  'gauge', 'activity', 'settings', 'percent',
  'wrench', 'zap', 'building',
  'normalize', 'export-roster',
  'today', 'week', 'month',
  'draft', 'safe', 'unsafe',
  'high-risk', 'mechanical', 'electrical', 'general',
  'operational',
  'home', 'chat', 'bell', 'history', 'pin', 'back', 'swap',
  'undo', 'redo', 'attachment', 'image', 'pdf', 'upload',
  'show', 'hide', 'department', 'font', 'grip',
  'zoom-in', 'zoom-out', 'accounts', 'app',
  'chevron-down', 'chevron-up', 'chevron-right', 'chevron-left', 'more', 'more-vertical', 'delete', 'copy', 'external', 'user', 'sign-out', 'sign-in', 'lock', 'info', 'help', 'arrow-up', 'arrow-down', 'save', 'print', 'funnel', 'sync', 'link', 'shield', 'key', 'camera', 'microphone', 'columns', 'sidebar', 'error', 'cancel', 'reset', 'empty',
] as const;

export type IconMeaning = (typeof ICON_MEANINGS)[number];


const LABEL_ALIASES: Record<string, IconMeaning> = {
  'total staff': 'employees',
  'total': 'employees',
  'total records': 'issues',
  'artisans': 'artisans',
  nec: 'nec-staff',
  salaried: 'salaried-staff',
  permanent: 'permanent-staff',
  'total equipment': 'equipment',
  equipment: 'equipment',
  operational: 'operational',
  maintenance: 'maintenance',
  breakdown: 'breakdown',
  availability: 'availability',
  'avg availability': 'availability',
  'total files': 'documents',
  'storage used': 'storage',
  starred: 'starred',
  'total items': 'spares',
  'total value': 'value',
  'out of stock': 'out-of-stock',
  'low stock': 'low-stock',
  categories: 'categories',
  'safety stock': 'spares',
  'total drivers': 'drivers',
  departments: 'departments',
  pending: 'pending',
  approved: 'success',
  critical: 'critical',
  'total notices': 'notice',
  active: 'active',
  pinned: 'pinned',
  expired: 'expired',
  certifications: 'training',
  compliance: 'compliance',
  valid: 'valid',
  'due soon': 'due-soon',
  today: 'today',
  'this week': 'week',
  recipients: 'recipients',
  'total cost': 'cost',
  'total care': 'care',
  draft: 'draft',
  submitted: 'submitted',
  reviewed: 'reviewed',
  closed: 'closed',
  'total units': 'compressor',
  'running hours': 'activity',
  'avg efficiency': 'efficiency',
  'upcoming services': 'service',
  'urgent alerts': 'warning',
  'total readings': 'activity',
  caution: 'warning',
  normal: 'success',
  current: 'valid',
  overdue: 'overdue',
  'total reports': 'notice',
  'in progress': 'pending',
  completed: 'success',
  mechanical: 'mechanical',
  electrical: 'electrical',
  general: 'general',
  unsafe: 'unsafe',
  safe: 'safe',
  actions: 'target',
  'high risk': 'high-risk',
  'below 90%': 'warning',
  'total downtime': 'clock',
  'records (period)': 'activity',
  'total requests': 'clock',
  'total hours': 'clock',
  'inactive / suspended': 'inactive',
  'current jobs': 'contractor',
  inactive: 'inactive',
  'not started': 'pending',
  'this month': 'month',
  'total assessed': 'training',
};


export const ICON_BY_MEANING: Record<IconMeaning, ElementType> = {
  employees: Users,
  artisans: HardHat,
  'nec-staff': IdentificationCard,
  'salaried-staff': CurrencyCircleDollar,
  'permanent-staff': UserCheck,
  'grid-view': SquaresFour,
  'list-view': List,
  'table-view': Table,
  'sheet-view': FileXls,
  search: MagnifyingGlass,
  filter: SlidersHorizontal,
  sort: ArrowsDownUp,
  edit: PencilSimple,
  mail: EnvelopeSimple,
  phone: Phone,
  archive: Archive,
  analytics: ChartLineUp,
  refresh: ArrowClockwise,
  download: DownloadSimple,
  plus: Plus,
  close: X,
  warning: Warning,
  success: CheckCircle,
  danger: Trash,
  clock: Clock,
  calendar: CalendarBlank,
  check: Check,
  pending: Clock,
  active: CheckCircle,
  inactive: Warning,
  equipment: Cube,
  maintenance: Gear,
  breakdown: Warning,
  availability: Percent,
  documents: File,
  storage: HardDrives,
  starred: Star,
  spares: Package,
  value: CurrencyCircleDollar,
  'out-of-stock': WarningOctagon,
  'low-stock': Warning,
  categories: CirclesFour,
  drivers: Car,
  departments: Buildings,
  requisition: ShoppingCart,
  cost: CurrencyCircleDollar,
  critical: Flag,
  notice: File,
  pinned: MapPin,
  expired: Clock,
  training: GraduationCap,
  compliance: CheckCircle,
  valid: CheckCircle,
  'due-soon': CalendarBlank,
  issues: Hash,
  recipients: Users,
  care: Heart,
  submitted: PaperPlaneTilt,
  reviewed: CheckCircle,
  closed: CheckSquare,
  compressor: Gauge,
  efficiency: TrendUp,
  service: Wrench,
  task: ClipboardText,
  overdue: Warning,
  ppe: HardHat,
  contractor: Handshake,
  'admin-role': Users,
  eye: Eye,
  target: Target,
  flag: Flag,
  cart: ShoppingCart,
  package: Package,
  gauge: Gauge,
  activity: Pulse,
  // Tools uses the spanner for Settings (and Wrench for maintenance); the two meanings share the glyph on purpose.
  settings: Wrench,
  percent: Percent,
  wrench: Wrench,
  zap: Lightning,
  building: Buildings,
  normalize: Sparkle,
  'export-roster': Medal,
  today: CalendarBlank,
  week: Rows,
  month: CalendarBlank,
  draft: File,
  safe: Eye,
  unsafe: Warning,
  'high-risk': Warning,
  mechanical: Wrench,
  electrical: Lightning,
  general: Buildings,
  operational: Pulse,
  home: House,
  chat: ChatCircleText,
  bell: Bell,
  history: ClockCounterClockwise,
  pin: MapPin,
  back: ArrowLeft,
  swap: ArrowsLeftRight,
  undo: ArrowUUpLeft,
  redo: ArrowUUpRight,
  attachment: Paperclip,
  image: ImageSquare,
  pdf: FilePdf,
  upload: UploadSimple,
  show: Eye,
  hide: EyeSlash,
  department: TreeStructure,
  font: TextAa,
  grip: DotsSixVertical,
  'zoom-in': MagnifyingGlassPlus,
  'zoom-out': MagnifyingGlassMinus,
  accounts: UserGear,
  app: Toolbox,
  'chevron-down': CaretDown,
  'chevron-up': CaretUp,
  'chevron-right': CaretRight,
  'chevron-left': CaretLeft,
  'more': DotsThree,
  'more-vertical': DotsThreeVertical,
  'delete': Trash,
  'copy': Copy,
  'external': ArrowSquareOut,
  'user': User,
  'sign-out': SignOut,
  'sign-in': SignIn,
  'lock': Lock,
  'info': Info,
  'help': Question,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'save': FloppyDisk,
  'print': Printer,
  'funnel': Funnel,
  'sync': ArrowsClockwise,
  'link': Link,
  'shield': ShieldCheck,
  'key': Key,
  'camera': Camera,
  'microphone': Microphone,
  'columns': Columns,
  'sidebar': SidebarSimple,
  'error': XCircle,
  'cancel': Prohibit,
  'reset': ArrowCounterClockwise,
  'empty': Cube,
};

export function meaningFromStatLabel(label: string): IconMeaning | undefined {
  const key = label.trim().toLowerCase();
  if (key in LABEL_ALIASES) return LABEL_ALIASES[key];
  if (key.includes('artisan')) return 'artisans';
  if (key === 'nec' || key.includes('nec staff')) return 'nec-staff';
  return undefined;
}

export function meaningFromViewValue(value: string): IconMeaning {
  if (value === 'grid' || value === 'card') return 'grid-view';
  if (value === 'table') return 'table-view';
  if (value === 'sheet') return 'sheet-view';
  return 'list-view';
}
