// Generates docs/MIGRATION_LEDGER.md: one row per App Router route.
//
// Objective columns come from the repository (what the page file does, which specs and unit tests exist).
// "Browser verified" is NEVER inferred: it is read from docs/migration-verification.json, which a person or
// agent edits only after actually rendering the page. A file existing, a build passing or a spec being
// present does not make a route verified.
//
//   node scripts/docs-ledger.mjs           rewrite docs/MIGRATION_LEDGER.md
//   node scripts/docs-ledger.mjs --check   exit 1 if the ledger is stale or a verification record is inconsistent
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const APP = path.join(root, 'app');
const LEDGER = path.join(root, 'docs', 'MIGRATION_LEDGER.md');
const VERIFICATION = path.join(root, 'docs', 'migration-verification.json');
const SPEC_DIR = path.join(root, 'scripts', 'route-specs');
// Routes covered by scripts/verify-registers.mjs (it predates the spec-driven runner).
const REGISTER_SCRIPT_ROUTES = ['/contractors', '/competency', '/compliance-register'];
// Routes that deliberately keep their own chrome rather than the shared shell.
const OWN_CHROME = { '/tools': 'Tools & Equipment workspace (its own layout; the visual standard)', '/login': 'sign-in page', '/auth/callback': 'auth redirect handler', '/auth/set-password': 'password setup' };

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === 'api' ? [] : walk(full);
    return entry.name === 'page.tsx' ? [full] : [];
  });
}

const routeOf = file => {
  const rel = path.relative(APP, path.dirname(file)).split(path.sep).join('/');
  return rel === '' ? '/' : `/${rel}`;
};

function codeStatus(route, source) {
  if (OWN_CHROME[route]) return 'own-chrome';
  if (/redirect\(/.test(source) && source.split('\n').length < 20) return 'redirect';
  if (/<AppShell migrated/.test(source)) return 'migrated';
  return 'legacy';
}

const specRoutes = new Set(REGISTER_SCRIPT_ROUTES);
for (const file of fs.existsSync(SPEC_DIR) ? fs.readdirSync(SPEC_DIR).filter(f => f.endsWith('.mjs')) : []) {
  const match = fs.readFileSync(path.join(SPEC_DIR, file), 'utf8').match(/route:\s*'([^']+)'/);
  if (match) specRoutes.add(match[1]);
}

const verification = fs.existsSync(VERIFICATION) ? JSON.parse(fs.readFileSync(VERIFICATION, 'utf8')) : { routes: {} };
const files = walk(APP).sort((a, b) => routeOf(a).localeCompare(routeOf(b)));
const rows = files.map(file => {
  const route = routeOf(file);
  const source = fs.readFileSync(file, 'utf8');
  const dir = path.dirname(file);
  const unitTests = fs.readdirSync(dir).filter(f => /\.test\.(ts|tsx)$/.test(f)).length;
  return { route, lines: source.split('\n').length, code: codeStatus(route, source), spec: specRoutes.has(route), unitTests, record: verification.routes?.[route] };
});

const problems = [];
for (const row of rows) {
  if (row.record?.status === 'verified' && row.code !== 'migrated' && row.code !== 'redirect') problems.push(`${row.route}: marked verified but is not migrated (${row.code})`);
  if (row.code === 'migrated' && !row.record) problems.push(`${row.route}: migrated but has no entry in docs/migration-verification.json (record what was actually rendered, or mark it explicitly unverified)`);
  if (row.code === 'migrated' && !row.spec) problems.push(`${row.route}: migrated but no automated route spec (scripts/route-specs)`);
}
for (const route of Object.keys(verification.routes ?? {})) if (!rows.some(r => r.route === route)) problems.push(`${route}: in docs/migration-verification.json but no such route`);

const label = { migrated: 'Migrated', legacy: 'Legacy body', redirect: 'Redirect', 'own-chrome': 'Own chrome' };
const count = key => rows.filter(r => r.code === key).length;
const verified = rows.filter(r => r.record?.status === 'verified').length;
const table = rows.map(r => {
  const v = r.record ? (r.record.status === 'verified' ? `Yes, ${r.record.date}` : `${r.record.status} (${r.record.date})`) : 'Not checked';
  const note = OWN_CHROME[r.route] ?? r.record?.note ?? '';
  return `| \`${r.route}\` | ${label[r.code]} | ${r.spec ? 'Yes' : 'No'} | ${r.unitTests || 'No'} | ${v} | ${note.replace(/\|/g, '/')} |`;
}).join('\n');

const markdown = `# Migration ledger

> **Generated by \`npm run docs:ledger\`; do not edit by hand.** Objective columns are read from the repository.
> "Browser verified" comes only from [\`migration-verification.json\`](./migration-verification.json), which is edited
> by hand after a page has actually been rendered and inspected. See [CURRENT_HANDOFF.md](./CURRENT_HANDOFF.md).

**${rows.length} routes.** Migrated: ${count('migrated')}. Legacy page body on the new shell: ${count('legacy')}. Redirects: ${count('redirect')}. Own chrome: ${count('own-chrome')}. Browser verified: ${verified}.

| Column | Meaning |
|---|---|
| Code | **Migrated**: the page renders \`<AppShell migrated>\` built from \`components/ui-system\`. **Legacy body**: the shell is new but the page still uses the old design-system components. **Redirect**: retired page that redirects. **Own chrome**: intentionally outside the shared shell. |
| Route spec | A spec in \`scripts/route-specs/\` (or the register script) exists. It drives ready, empty, failed-load, create-flow and 390 px checks with a fixture session and mocked API. A spec existing is not the same as it having been run recently; the date in the next column is. |
| Unit tests | Number of \`*.test.ts(x)\` files beside the page. Shared logic has its own tests (see [TESTING.md](./TESTING.md)). |
| Browser verified | A recorded, dated rendering of the route at 1440 and 390 px with screenshots inspected. Never inferred. |

| Route | Code | Route spec | Unit tests | Browser verified | Note |
|---|---|---|---|---|---|
${table}
${problems.length ? `\n## Inconsistencies\n\n${problems.map(p => `- ${p}`).join('\n')}\n` : ''}`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(LEDGER) ? fs.readFileSync(LEDGER, 'utf8') : '';
  let failed = false;
  if (current.replace(/\r\n/g, '\n') !== markdown) { console.error('docs/MIGRATION_LEDGER.md is stale. Run `npm run docs:ledger` and commit the result.'); failed = true; }
  if (problems.length) { console.error(`Migration ledger inconsistencies:\n${problems.map(p => `  - ${p}`).join('\n')}`); failed = true; }
  if (failed) process.exit(1);
  console.log(`Migration ledger is current (${rows.length} routes, ${count('migrated')} migrated, ${verified} browser verified).`);
} else {
  fs.writeFileSync(LEDGER, markdown);
  console.log(`Wrote docs/MIGRATION_LEDGER.md (${rows.length} routes, ${count('migrated')} migrated, ${verified} browser verified).${problems.length ? `\n${problems.length} inconsistencies listed in the file.` : ''}`);
}
