// Generates docs/WIREFRAME_LEDGER.md from docs/wireframe-ledger.json. The stage columns come only from the JSON.
//   node scripts/wireframe-ledger.mjs
import fs from 'node:fs';

const data = JSON.parse(fs.readFileSync('docs/wireframe-ledger.json', 'utf8')).routes;
const names = { R: 'Register', D: 'Dashboard', Rp: 'Report', W: 'Workflow or entry', G: 'Planning grid', A: 'Administration', H: 'Hub', X: 'Own chrome' };
const rows = Object.entries(data).sort(([a], [b]) => a.localeCompare(b));
const count = f => rows.filter(([, r]) => f(r)).length;
const lines = [
  '# Wireframe ledger', '',
  '> **Generated by `node scripts/wireframe-ledger.mjs`; do not edit by hand.** Source: [wireframe-ledger.json](./wireframe-ledger.json).',
  '> Patterns are defined in [PAGE_PATTERNS.md](./PAGE_PATTERNS.md). "Current" is measured from the rendered page.', '',
  `**${rows.length} routes.** Built from the shared pattern components: ${count(r => r.implemented)}. Layout verified in the rendered app: ${count(r => r.layoutVerified)}. Overlays reviewed: ${count(r => r.overlaysReviewed)}.`, '',
  '| Stage | Meaning |', '|---|---|',
  '| Current | Measured from the page at 1440 px: title, tabs, tables, cards, inputs and selects. |',
  '| Recommended | The pattern and what the page should change to. |',
  '| Implemented | The route is built from the shared pattern components (`AppShell migrated`). |',
  '| Layout verified | The route was rendered at desktop, tablet and phone size after implementation and its layout inspected (date). |',
  '| Overlays reviewed | Every dialog, menu and popover the route opens was opened and inspected (date). |', '',
  '| Route | Pattern | Current | Recommended | Implemented | Layout verified | Overlays reviewed |', '|---|---|---|---|---|---|---|',
  ...rows.map(([route, r]) => `| \`${route}\` | ${names[r.pattern] ?? r.pattern} | ${r.current} | ${r.recommended} | ${r.implemented ? 'Yes' : 'No'} | ${r.layoutVerified ?? 'No'} | ${r.overlaysReviewed ?? 'No'} |`),
  '',
];
fs.writeFileSync('docs/WIREFRAME_LEDGER.md', lines.join('\n'));
console.log(`Wrote docs/WIREFRAME_LEDGER.md (${rows.length} routes)`);
