/** Dallaglio glyph map — Tools stroke set (Phosphor light), not Classic aliases. */

import type { ElementType } from 'react';
import type { IconMeaning } from '../shared/icon-meanings';
import {
  Archive, ArrowClockwise, ArrowLeft, ArrowsDownUp, ArrowsLeftRight, ArrowUUpLeft, ArrowUUpRight,
  Bell, ChartLineUp, ChatCircleText, Check,
  CheckCircle, ClipboardText, Clock, ClockCounterClockwise, Cube, CurrencyCircleDollar, DownloadSimple,
  DotsSixVertical, Eye, EyeSlash, File, FilePdf, FileXls, Flag, Gauge, Gear, GraduationCap, HardHat,
  Handshake, Hash, Heart, House, IdentificationCard, ImageSquare, Lightning, List, MagnifyingGlass,
  MagnifyingGlassMinus, MagnifyingGlassPlus, Medal, Package, Paperclip, Percent, PencilSimple, Plus, ShoppingCart, SlidersHorizontal,
  Pulse, Sparkle, SquaresFour, Star, Table, Target, TextAa, Toolbox, Trash, TreeStructure, TrendUp,
  UploadSimple, UserCheck, UserGear, Users,
  Warning, WarningOctagon, Wrench, Buildings, Car, CalendarBlank,
  HardDrives, MapPin, PaperPlaneTilt, CheckSquare, X, CirclesFour, Rows, EnvelopeSimple, Phone,
} from '../icons';

export const DALLAGLIO_ICONS: Record<IconMeaning, ElementType> = {
  employees: Users,
  artisans: HardHat,
  'nec-staff': IdentificationCard,
  'salaried-staff': CurrencyCircleDollar,
  'permanent-staff': UserCheck,
  'grid-view': SquaresFour,
  'list-view': List,
  'table-view': Table,
  'sheet-view': FileXls,
  search: MagnifyingGlass,
  filter: SlidersHorizontal,
  sort: ArrowsDownUp,
  edit: PencilSimple,
  mail: EnvelopeSimple,
  phone: Phone,
  archive: Archive,
  analytics: ChartLineUp,
  refresh: ArrowClockwise,
  download: DownloadSimple,
  plus: Plus,
  close: X,
  warning: Warning,
  success: CheckCircle,
  danger: Trash,
  clock: Clock,
  calendar: CalendarBlank,
  check: Check,
  pending: Clock,
  active: CheckCircle,
  inactive: Warning,
  equipment: Cube,
  maintenance: Gear,
  breakdown: Warning,
  availability: Percent,
  documents: File,
  storage: HardDrives,
  starred: Star,
  spares: Package,
  value: CurrencyCircleDollar,
  'out-of-stock': WarningOctagon,
  'low-stock': Warning,
  categories: CirclesFour,
  drivers: Car,
  departments: Buildings,
  requisition: ShoppingCart,
  cost: CurrencyCircleDollar,
  critical: Flag,
  notice: File,
  pinned: MapPin,
  expired: Clock,
  training: GraduationCap,
  compliance: CheckCircle,
  valid: CheckCircle,
  'due-soon': CalendarBlank,
  issues: Hash,
  recipients: Users,
  care: Heart,
  submitted: PaperPlaneTilt,
  reviewed: CheckCircle,
  closed: CheckSquare,
  compressor: Gauge,
  efficiency: TrendUp,
  service: Wrench,
  task: ClipboardText,
  overdue: Warning,
  ppe: HardHat,
  contractor: Handshake,
  'admin-role': Users,
  eye: Eye,
  target: Target,
  flag: Flag,
  cart: ShoppingCart,
  package: Package,
  gauge: Gauge,
  activity: Pulse,
  settings: Gear,
  percent: Percent,
  wrench: Wrench,
  zap: Lightning,
  building: Buildings,
  normalize: Sparkle,
  'export-roster': Medal,
  today: CalendarBlank,
  week: Rows,
  month: CalendarBlank,
  draft: File,
  safe: Eye,
  unsafe: Warning,
  'high-risk': Warning,
  mechanical: Wrench,
  electrical: Lightning,
  general: Buildings,
  operational: Pulse,
  home: House,
  chat: ChatCircleText,
  bell: Bell,
  history: ClockCounterClockwise,
  pin: MapPin,
  back: ArrowLeft,
  swap: ArrowsLeftRight,
  undo: ArrowUUpLeft,
  redo: ArrowUUpRight,
  attachment: Paperclip,
  image: ImageSquare,
  pdf: FilePdf,
  upload: UploadSimple,
  show: Eye,
  hide: EyeSlash,
  department: TreeStructure,
  font: TextAa,
  grip: DotsSixVertical,
  'zoom-in': MagnifyingGlassPlus,
  'zoom-out': MagnifyingGlassMinus,
  accounts: UserGear,
  app: Toolbox,
};

export const DALLAGLIO_ICON_WEIGHT = 'light' as const;
export const DALLAGLIO_ICON_SIZE = 16;
