// components/shared/design-system/icons.tsx — THE single icon source for the app.
// Every icon is a Phosphor glyph re-exported under the app's existing logical name
// (the names the codebase already used from lucide), so call sites keep using
// `<Users/>`, `icon={Trash2}`, etc. unchanged.
//
// Solid vs. outline is a GLOBAL preference: IconStyleProvider (below) sets Phosphor's
// IconContext `weight` ('fill' = solid, 'regular' = outline) for every icon at once,
// toggled from the header (TopNavigation) and persisted to localStorage.
//
// RULE: import icons from here (via the '@/components/shared/theme' barrel), NEVER
// directly from '@/components/shared/theme'/'@phosphor-icons/react' — a direct import won't respond
// to the outline/solid toggle and breaks the single-family look.
//
// This file is generated from a name map (see build_map.mjs in git history); to add
// an icon, add a re-export line for the logical name you need.
'use client';

import { createContext, useContext, useState, useEffect, useMemo, type ReactNode, type ElementType } from 'react';
import { IconContext } from '@phosphor-icons/react';

// Type alias for an icon component prop (was lucide's `LucideIcon`); ElementType
// accepts any icon component (Phosphor, custom SVG) passed to an `icon={}` prop.
export type LucideIcon = ElementType;

// ─── Re-exported icon set (logical app name ← Phosphor glyph) ────────────────
export {
  Pulse as Activity,
  Alarm as AlarmClock,
  WarningCircle as AlertCircle,
  WarningOctagon as AlertOctagon,
  Warning as AlertTriangle,
  TextAlignLeft as AlignLeft,
  AppleLogo as Apple,
  Archive,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowsDownUp as ArrowUpDown,
  ArrowUpRight,
  Medal as Award,
  Medal as AwardIcon,
  Baby,
  SealCheck as Badge,
  SealCheck as BadgeCheck,
  Prohibit as Ban,
  Money as Banknote,
  ChartBar as BarChart,
  ChartBar as BarChart2,
  ChartBar as BarChart3,
  Bathtub as Bath,
  Bed,
  Cow as Beef,
  BeerBottle as Beer,
  Bell,
  TextB as Bold,
  BookBookmark as BookHeart,
  BookmarkSimple as Bookmark,
  BookBookmark as BookMarked,
  BookOpen,
  Package as Box,
  Stack as Boxes,
  Brain,
  Briefcase,
  Briefcase as BriefcaseBusiness,
  PaintBrush as Brush,
  Buildings as Building,
  Buildings as Building2,
  Cake,
  Calculator,
  Calendar,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CalendarX as CalendarOff,
  CalendarBlank as CalendarRange,
  Camera,
  Car,
  Carrot,
  Cat,
  Check,
  Checks as CheckCheck,
  CheckCircle,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CheckSquare,
  CookingPot as ChefHat,
  CookingPot as ChefHatIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretDoubleDown as ChevronsDown,
  ArrowsInLineVertical as ChevronsDownUp,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleRight as ChevronsRight,
  CaretDoubleUp as ChevronsUp,
  ArrowsOutLineVertical as ChevronsUpDown,
  CaretUp as ChevronUp,
  CaretUp as ChevronUpIcon,
  Church,
  Circle,
  CheckCircle as CircleCheckIcon,
  CurrencyCircleDollar as CircleDollarSign,
  Circle as CircleIcon,
  ClipboardText as ClipboardCheck,
  ClipboardText as ClipboardList,
  Clipboard as ClipboardPlus,
  Clock,
  Clock as Clock3,
  Clock as Clock4,
  Cloud,
  CloudRain,
  Coffee,
  Coffee as CoffeeIcon,
  Gear as Cog,
  Coins,
  Columns,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  CreditCard as CreditCardIcon,
  Cross,
  Crown,
  Database,
  Diamond,
  Dog,
  CurrencyDollar as DollarSign,
  Door as DoorOpen,
  DownloadSimple as Download,
  CloudArrowDown as DownloadCloud,
  Drop as Droplet,
  Drop as Droplets,
  Cow as Drumstick,
  PencilSimple as Edit,
  PencilSimple as Edit2,
  PencilSimple as Edit3,
  Egg as EggFried,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FacebookLogo as Facebook,
  Factory,
  Fan,
  File,
  PresentationChart as FileBarChart,
  SealCheck as FileCheck,
  FileText as FileCheck2,
  FileArrowDown as FileDown,
  FileText as FileEdit,
  FileText as FilePieChart,
  FilePlus,
  FileMagnifyingGlass as FileSearch,
  FileText as FileSignature,
  FileXls as FileSpreadsheet,
  FileText,
  FileArrowUp as FileUp,
  IdentificationCard as FileUser,
  WarningDiamond as FileWarning,
  FilmSlate as Film,
  Funnel as Filter,
  FunnelX as FilterX,
  Fish,
  Flag,
  Flame,
  Flame as FlameIcon,
  Flashlight,
  Flask as FlaskConical,
  Flower,
  Folder,
  FolderOpen,
  FolderPlus,
  GasPump as Fuel,
  Gauge,
  Diamond as Gem,
  Gift,
  GitBranch,
  GitDiff as GitCompare,
  Globe,
  GraduationCap,
  GridFour as Grid,
  GridFour as Grid2X2,
  GridNine as Grid3x3,
  GridNine as Grid3X3,
  DotsSixVertical as GripVertical,
  // PPE-item glyphs (app/ppe) — grouped here rather than sorted in, since hunting exact
  // alphabetical position by export name across this generated file isn't worth it for
  // a one-time hand addition.
  Belt,
  Boot,
  BoxingGlove,
  Dress,
  FaceMask,
  Goggles,
  Hoodie,
  Pants,
  Seatbelt,
  ShirtFolded,
  Sneaker,
  HandCoins,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Heart,
  Handshake as HeartHandshake,
  Heartbeat as HeartPulse,
  Question as HelpCircle,
  Hexagon,
  ClockCounterClockwise as History,
  House as Home,
  IceCream,
  Image,
  Image as ImageIcon,
  Info,
  Info as InfoIcon,
  InstagramLogo as Instagram,
  TextItalic as Italic,
  Key,
  Bank as Landmark,
  Laptop,
  Stack as Layers,
  Layout,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Leaf,
  Books as Library,
  Lightbulb,
  ChartLine as LineChart,
  Link,
  Link as Link2,
  LinkedinLogo as Linkedin,
  List,
  TreeStructure as ListTree,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  Lock,
  SignIn as LogIn,
  SignOut as LogOut,
  Envelope as Mail,
  Mailbox,
  MapTrifold as Map,
  MapPin,
  MapPin as MapPinIcon,
  Martini,
  ArrowsOut as Maximize2,
  Megaphone,
  Memory as MemoryStick,
  List as Menu,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  ChatCenteredDots as MessageSquareWarning,
  Microphone as Mic,
  Drop as Milk,
  ArrowsIn as Minimize2,
  Minus,
  Monitor,
  Moon,
  DotsThree as MoreHorizontal,
  DotsThreeVertical as MoreVertical,
  ArrowsVertical as MoveVertical,
  MusicNote as Music,
  NavigationArrow as Navigation,
  Graph as Network,
  Newspaper,
  Octagon,
  XCircle as OctagonXIcon,
  Package,
  HandDeposit as PackageMinus,
  Package as PackageOpen,
  PaintBucket,
  Palette,
  SidebarSimple as PanelLeftClose,
  Sidebar as PanelLeftOpen,
  Paperclip,
  Confetti as PartyPopper,
  Pause,
  PauseCircle,
  PencilSimple as Pen,
  PencilSimple as Pencil,
  PencilSimpleLine as PenLine,
  PenNib as PenTool,
  Percent,
  DeviceMobile as Phone,
  PhoneCall,
  ChartPie as PieChart,
  PushPin as Pin,
  PushPinSlash as PinOff,
  Pizza,
  Play,
  PlayCircle,
  Plus,
  MicrophoneStage as Podcast,
  Power,
  Printer,
  Presentation as Projector,
  Quotes as Quote,
  Broadcast as Radar,
  Radio,
  Receipt,
  ArrowsClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  Repeat as Repeat2,
  ArrowCounterClockwise as RotateCcw,
  BowlFood as Salad,
  Hamburger as Sandwich,
  FloppyDisk as Save,
  Scales as Scale,
  Scan,
  ChartScatter as ScatterChart,
  Scissors,
  MagnifyingGlass as Search,
  MagnifyingGlass as SearchIcon,
  PaperPlaneTilt as Send,
  HardDrives as Server,
  Gear as Settings,
  GearSix as Settings2,
  ShareNetwork as Share2,
  Spiral as Shell,
  Shield,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  Shield as ShieldIcon,
  TShirt as Shirt,
  ShoppingBag,
  Basket as ShoppingBasket,
  ShoppingCart,
  Signature,
  FadersHorizontal as SlidersHorizontal,
  DeviceMobile as Smartphone,
  Smiley as Smile,
  Snowflake,
  SortAscending as SortAsc,
  SortDescending as SortDesc,
  BowlFood as Soup,
  Sparkle,
  Sparkle as Sparkles,
  SpeakerHigh as Speaker,
  Square,
  Star,
  Stethoscope,
  Storefront as Store,
  Storefront as StoreIcon,
  Sun,
  SunHorizon as Sunrise,
  SunHorizon as Sunset,
  Table,
  Table as Table2,
  DeviceTablet as Tablet,
  Tag,
  Target,
  TextT as TextCursor,
  Thermometer,
  Thermometer as ThermometerSun,
  ThumbsUp,
  Timer,
  Toolbox as ToolCase,
  Tractor,
  Trash,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Triangle,
  Warning as TriangleAlertIcon,
  Trophy,
  Truck,
  Truck as TruckIcon,
  Television as Tv,
  TwitterLogo as Twitter,
  TextT as Type,
  Umbrella,
  LockOpen as Unlock,
  UploadSimple as Upload,
  CloudArrowUp as UploadCloud,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  User as UserRound,
  Users,
  Users as UsersRound,
  UserMinus as UserX,
  ForkKnife as Utensils,
  ForkKnife as UtensilsCrossed,
  VideoCamera as Video,
  SpeakerHigh as Volume2,
  Wallet,
  MagicWand as Wand2,
  Warehouse,
  Watch,
  Waves,
  Plant as Wheat,
  WifiHigh as Wifi,
  Wind,
  Wine,
  Wine as WineIcon,
  FlowArrow as Workflow,
  Wrench,
  X,
  XCircle,
  X as XIcon,
  YoutubeLogo as Youtube,
  Lightning as Zap,
  LightningSlash as ZapOff,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
} from '@phosphor-icons/react';

// Extra UI glyph for the design system's own icon-style toggle indicator.
export { CircleHalf as IconStyleGlyph } from '@phosphor-icons/react';

// Additional logical names used by legacy .js components (maintenance, forms, etc.).
export {
  BatteryCharging,
  HouseLine,
  Kanban,
  ListChecks as ListTodo,
  QrCode,
  Rocket,
  TextAa,
  Wrench as Tool,
} from '@phosphor-icons/react';

// ─── Icon-style preference (solid/outline), persisted, default solid ─────────
export type IconStyle = 'solid' | 'outline';
const ICON_STYLE_KEY = 'oz_iconStyle';

type IconStyleContextValue = {
  iconStyle: IconStyle;
  setIconStyle: (s: IconStyle) => void;
  toggleIconStyle: () => void;
};
const IconStyleContext = createContext<IconStyleContextValue>({
  iconStyle: 'solid', setIconStyle: () => {}, toggleIconStyle: () => {},
});
export const useIconStyle = () => useContext(IconStyleContext);

/** App-wide icon-style provider — mount once near the root (components/Providers.tsx),
 *  inside ThemeProvider is fine. Bridges the persisted preference to Phosphor's
 *  IconContext `weight`, so every Phosphor icon flips solid↔outline together. */
export function IconStyleProvider({ children }: { children: ReactNode }) {
  const [iconStyle, setIconStyleState] = useState<IconStyle>('solid');
  useEffect(() => {
    try {
      const s = localStorage.getItem(ICON_STYLE_KEY);
      if (s === 'solid' || s === 'outline') setIconStyleState(s);
    } catch { /* storage unavailable — keep default */ }
  }, []);
  const setIconStyle = (s: IconStyle) => {
    setIconStyleState(s);
    try { localStorage.setItem(ICON_STYLE_KEY, s); } catch { /* non-fatal */ }
  };
  useEffect(() => { document.documentElement.dataset.iconStyle = iconStyle; }, [iconStyle]);
  const value = useMemo<IconStyleContextValue>(() => ({
    iconStyle, setIconStyle,
    toggleIconStyle: () => setIconStyle(iconStyle === 'solid' ? 'outline' : 'solid'),
  }), [iconStyle]);
  return (
    <IconStyleContext.Provider value={value}>
      {/* size:24 (not Phosphor's '1em' default) matches lucide-react's original 24px
          default, so any icon rendered WITHOUT an explicit size class / `size` prop keeps
          its pre-migration size. Icons with Tailwind h-/w-/size-* (CSS) or an explicit
          `size` prop override this, so they're unaffected. */}
      <IconContext.Provider value={{ color: 'currentColor', size: 24, weight: iconStyle === 'solid' ? 'fill' : 'regular', mirrored: false }}>
        {children}
      </IconContext.Provider>
    </IconStyleContext.Provider>
  );
}
